
import java.util.ArrayList;
import oregontrailpackage.FileAssist;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bo
 */
public class FileWriter extends javax.swing.JFrame
{
    /*
    This is a thing I whipped up that makes it really easy to write the text 
    files in a way that the program can read. Just run the file and if using it 
    is confusing just ask me to take 2 minutes and show you how it works.
    */
    
    String[] types = new String[]{"Trail", "River", "Fort", "City", "Landmark"};
    String[][] typeSections = new String[][]
    {
        {"Name", "Description", "PreviousLocations", "NextLocations", "MenuOptions", "Terrain", "Distance"},
        {"Name", "Description", "PreviousLocations", "NextLocations", "MenuOptions", "MaxDepth", "MinDepth", "MaxWidth", "MinWidth"},
        {"Name", "Description", "PreviousLocations", "NextLocations", "MenuOptions", "Ammunition", "Clothes", "Food", "Oxen", "Wheels", "Axles", "Tongues"},
        {"Name", "Description", "PreviousLocations", "NextLocations", "MenuOptions", "Ammunition", "Clothes", "Food", "Oxen", "Wheels", "Axles", "Tongues"},
        {"Name", "Description", "PreviousLocations", "NextLocations", "MenuOptions"}
    };
    JPanel panel = new JPanel(new GridLayout(0,1));
    /**
     * Creates new form FileWriter
     */
    public FileWriter()
    {
        initComponents();
        mainPane.getViewport().setView(panel);
    }

    public void writeFile()
    {
        ArrayList<String> sections = new ArrayList<String>();
        ArrayList<ArrayList<String>> data = new ArrayList<ArrayList<String>>();
        
        //add type
        sections.add("Type");
        ArrayList<String> typeData = new ArrayList<String>();
        typeData.add(typeBox.getSelectedItem().toString());
        data.add(typeData);
        
        //add sections and data from panel
        for(int i = 0; i < panel.getComponentCount(); i++)
        {
            JPanel sectionPanel = (JPanel)panel.getComponent(i);
            TitledBorder border = (TitledBorder)sectionPanel.getBorder();
            sections.add(border.getTitle());
            
            ArrayList<String> sectionData = new ArrayList<String>();
            for(int o = 0; o < sectionPanel.getComponentCount(); o++)
            {
                JPanel linePanel = (JPanel)sectionPanel.getComponent(o);
                JTextField field = (JTextField)linePanel.getComponent(0);//zero is intentional
                if(!field.getText().equals(""))
                    sectionData.add(field.getText());
            }
            data.add(sectionData);
        }
        
        //actually write file from gathered data
        FileAssist test = new FileAssist(filenameTextField.getText());
        test.createFile();
        for(int i = 0; i < sections.size(); i++)
        {
            test.addSection(sections.get(i));
            test.setLinesIn(sections.get(i), data.get(i));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        filenameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        typeBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        writeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filenameTextField.setToolTipText("Press enter to load file");
        filenameTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                filenameTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText(".txt");

        typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trail", "River", "Fort", "City", "Landmark" }));
        typeBox.setToolTipText("Generate appropriate sections\\n(Will empty all fields)");
        typeBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                typeBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
            .addComponent(filenameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        writeButton.setText("Write File");
        writeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                writeButtonActionPerformed(evt);
            }
        });
        jPanel3.add(writeButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldActionPerformed(ActionEvent e)
    {
        JTextField field = (JTextField)e.getSource();
        if(field.getText().length() == 0)return;
        
        //this is the section panel. just trust me on this
        JPanel sectionPanel = (JPanel)field.getParent().getParent();
        
        //add a new "line"
        JPanel linePanel = getLine();
        sectionPanel.add(linePanel);
        
        validate();
        linePanel.getComponent(0).requestFocusInWindow();
    }

    private void writeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_writeButtonActionPerformed
    {//GEN-HEADEREND:event_writeButtonActionPerformed
        writeFile();
    }//GEN-LAST:event_writeButtonActionPerformed

    private void filenameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_filenameTextFieldActionPerformed
    {//GEN-HEADEREND:event_filenameTextFieldActionPerformed
        FileAssist file = new FileAssist(filenameTextField.getText());
        if(file.exists())
        {
            //figure out type
            String typeS = file.getLineIn("Type");
            int type = 0;
            for(int i = 0; i < types.length; i++)
                if(types[i].equals(typeS))
                {
                    type = i;
                    break;
                }
            typeBox.setSelectedIndex(type);
            panel.removeAll();
            
            
            ArrayList<String> sections = file.getSections();
            for(int i = 1; i < sections.size(); i++)//starts at 1, skips Type
            {
                JPanel sectionPanel = getSection(sections.get(i));
                
                ArrayList<String> lines = file.getLinesIn(sections.get(i));
                for(int o = 0; o < lines.size(); o++)
                {
                    JTextField field = (JTextField)((JPanel)(sectionPanel.getComponent(o))).getComponent(0);
                    field.setText(lines.get(o));
                    
                    sectionPanel.add(getLine());
                }
                
                panel.add(sectionPanel);
            }
            validate();
        }//if file exists
    }//GEN-LAST:event_filenameTextFieldActionPerformed

    private void typeBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_typeBoxActionPerformed
    {//GEN-HEADEREND:event_typeBoxActionPerformed
        int type = typeBox.getSelectedIndex();
        
        panel.removeAll();
        
        String[] sections = typeSections[type];
        for(String section: sections)
        {
            panel.add(getSection(section));
        }
        validate();
    }//GEN-LAST:event_typeBoxActionPerformed

    
    private JPanel getSection(String title)
    {
        JPanel sectionPanel = new JPanel(new GridLayout(0,1));
        sectionPanel.setBorder(new TitledBorder(title));
        sectionPanel.add(getLine());
        return sectionPanel;
    }
    
    private JPanel getLine()
    {
        JPanel linePanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
          JTextField field = new JTextField(20);
          field.addActionListener(new ActionListener()
          {
              public void actionPerformed(ActionEvent e)
              {
                  textFieldActionPerformed(e);
              }
          });
         linePanel.add(field);
         return linePanel;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FileWriter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FileWriter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FileWriter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FileWriter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FileWriter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filenameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane mainPane;
    private javax.swing.JComboBox<String> typeBox;
    private javax.swing.JButton writeButton;
    // End of variables declaration//GEN-END:variables
}
